name: mask-test

on:
  workflow_dispatch:  # run manually

jobs:
  mask-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: mask-test
        run: |
          echo "hw"
          echo "::add-mask::my-secret-value"
          for i in {1..500}; do
            echo "::add-mask::my-secret-value$i"
          done
          echo "my-secret-value399"
          echo "my-secret-value599"
          echo "my-secret-value499"

