name: mask-test

on:
  workflow_dispatch:  # run manually
  push:
    branches:
    - "**"

jobs:
  mask-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: mask-operations-count
        run: |
          echo "hw"
          echo "::add-mask::my-secret-value"
          for i in {1..50000}; do
            echo "::add-mask::my-secret-value$i"
          done
          echo "my-secret-value399"
          echo "my-secret-value599"
          echo "my-secret-value49908"

      - name: mask-size-test
        run: |
          echo "hw"
          long=$(printf 'A%.0s' {1..500000})
          echo ${#long}
          echo "::add-mask::$long"
          echo ${long}
